# -*- coding: utf-8 -*-
"""Deepfake_model_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrd_8Jzl-vejvDt_HQ3jAhD2NTzEQJJa
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!cp -r /content/drive/MyDrive/deepfake_dataset /content/

import tensorflow as tf
from tensorflow.keras import layers, Model

IMG_SIZE = 96
BATCH_SIZE = 32

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/deepfake_dataset",
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "/content/deepfake_dataset",
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE
)

train_ds = train_ds.map(lambda x, y: (x/255.0, y)).prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.map(lambda x, y: (x/255.0, y)).prefetch(tf.data.AUTOTUNE)

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
])

inputs = tf.keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))

x = data_augmentation(inputs)

# 🔥 CNN (FAST + EFFECTIVE)
x = layers.Conv2D(32, (3,3), activation="relu")(x)
x = layers.MaxPooling2D()(x)

x = layers.Conv2D(64, (3,3), activation="relu")(x)
x = layers.MaxPooling2D()(x)

x = layers.Conv2D(128, (3,3), activation="relu")(x)
x = layers.MaxPooling2D()(x)

x = layers.Flatten()(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.5)(x)

outputs = layers.Dense(1, activation="sigmoid")(x)

model = Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

checkpoint = tf.keras.callbacks.ModelCheckpoint(
    "/content/drive/MyDrive/new_pipeline_model.keras",
    monitor="val_accuracy",
    save_best_only=True,
    verbose=1
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=5,
    steps_per_epoch=40,
    validation_steps=10,
    callbacks=[checkpoint]
)

model.save("/content/drive/MyDrive/final_cnn_74acc.keras")

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=3,
    steps_per_epoch=80,
    validation_steps=20,
    callbacks=[checkpoint]
)

model.save("/content/drive/MyDrive/final_cnn_74acc.keras")

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=2,
    steps_per_epoch=120,
    validation_steps=25,
    callbacks=[checkpoint]
)

model.save("/content/drive/MyDrive/model_78percent_final.keras")

import os

print(os.listdir("/content/drive/MyDrive"))

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=2,
    steps_per_epoch=150,
    validation_steps=30,
    callbacks=[checkpoint]
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/new_pipeline_model_v2.keras")

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=2,
    steps_per_epoch=90,
    validation_steps=20
)

from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/new_pipeline_model_v2.keras")

model.compile(
    optimizer=tf.keras.optimizers.Adam(5e-6),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=1,
    steps_per_epoch=80,
    validation_steps=20
)

from tensorflow.keras.models import load_model
import tensorflow as tf

# Load your best model
model = load_model("/content/drive/MyDrive/new_pipeline_model_v2.keras")

# Compile with VERY LOW LR (key step)
model.compile(
    optimizer=tf.keras.optimizers.Adam(2e-6),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Train (SAFE — no timeout)
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=1,
    steps_per_epoch=100,   # 🔥 slightly higher exposure
    validation_steps=20
)

model.save("/content/drive/MyDrive/final_model_79_stable.keras")

loss, acc = model.evaluate(val_ds)
print("Final Accuracy:", acc)

model.save("/content/drive/MyDrive/final_model_cnn.keras")

from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/final_model_cnn.keras")

loss, acc = model.evaluate(val_ds, steps=20)
print("Final CNN Accuracy:", acc)

from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/final_model_cnn.keras")



